### ISSUE TITLE
Clarify "stitched"

### ISSUE THREAD

**Issue by rvagg** [RUB-NDS/TLS-Padding-Oracles#2]
> only for non-stitched cipher suites, when AES-NI is not used

I'm having trouble finding anyone who understands the "stitched" terminology and can help explain this to a less cryptographically-educated audience. Is it referring to AE? So only non-AE/AEAD ciphersuites are vulnerable? Or is it connected to the use of AES-NI instructions, or is that a separate concern?

**Comment by cy1337** [comment]
"stitched" ciphers are basically those implementations which benefit from hardware acceleration. 

This document from Intel may help clarify: https://software.intel.com/en-us/articles/improving-openssl-performance

**Comment by rvagg** [comment]
thanks for clarifying, maybe that link would be helpful in the article for the word "stitched"
