### ISSUE TITLE
padding byte should be 0x07 for 7 bytes?

### ISSUE THREAD

**Issue by saravananmk** [RUB-NDS/TLS-Padding-Oracles#5]
Hi Juraj,

On this page "https://github.com/RUB-NDS/TLS-Padding-Oracles" under the section "CBC and its usage in the TLS record layer", it says:

> The second block needs to be padded with 7 bytes 0x06. 

For 7 bytes of padding, the padding byte should be 0x07 right?  Why it says 0x06?

with regards,
Saravanan

**Comment by ic0ns** [comment]
Hey saravananmk,
in TLS the last padding byte is equal to the number of the remaining padding bytes. Those are then just filled with the same byte till the padding is full. This is different to what you usually see if you have padding according to RFC 2040. This means that 06060606060606 for a 7 Byte padding is infact correct. 
This has mostly historic reasons as SSL 3 had a similar padding and was simply upgraded.
cheers
Robert
